spring.application.name=BillingSoft

spring.datasource.url=jdbc:postgresql://astranexis-billingsoft-sachidanand-aiven-2023.i.aivencloud.com:22261/Billing?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_1S8Gko5MrivGg8hGI8m
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
